In [1]:
import numpy as np
import pandas as pd

/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [3]:
data = pd.read_csv("play_tennis.csv")

In [5]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [ ]:
# Problem 1
# Outllook=Sunny, temp=hot, humidilt=high, wind=weak
# paly or not play ??

In [9]:
# Solution
# P(Yes | Sunny,hot,high,weak) = P(Sunny| Yes) * P(Hot|Yes) * P(High| Yes) * P(Weak | Yes) * P(Yes)
# P(No | Sunny,hot,high,weak) = P(Sunny| No) * P(Hot|No) * P(High| No) * P(Weak | No) * P(No)
# compare and decide using the Maximum a posteriori Rule

In [11]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [13]:
py = 9/14
pn = 5/14

In [15]:
print(py,pn)

0.6428571428571429 0.35714285714285715

In [17]:
# respective probability
# outlook column
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [23]:
Play_overcast_no = 0
Play_rain_no = 2/5
Play_sunny_no = 3/5

Play_overcast_yes = 4/9
Play_rain_yes = 3/9
Play_sunny_yes = 2/9

In [25]:
# temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [27]:
Play_cool_no = 1/5
Play_hot_no = 2/5
Play_mild_no = 2/5

Play_cool_yes = 3/9
Play_hot_yes = 2/9
Play_mild_yes = 4/9

In [29]:
# Humidity

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [31]:
Play_high_no = 4/5
Play_normal_no = 1/5

Play_high_yes = 3/9
Play_normal_yes = 6/9

In [33]:
# wind

pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [35]:
Play_strong_no = 3/5
Play_weak_no = 2/5
Play_strong_yes = 3/9
Play_weak_yes = 6/9

In [39]:
# Outllook=Sunny, temp=hot, humidilt=high, wind=weak

p_yes = py*Play_sunny_yes*Play_hot_yes*Play_high_yes*Play_weak_yes
p_no = pn*Play_sunny_no*Play_hot_no*Play_high_no*Play_weak_no

In [41]:
print(p_yes, p_no)

0.007054673721340388 0.02742857142857143